AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-hello-api

  Sample SAM Template for lambda-hello-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15 # Adjust the timeout as needed (in seconds)

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: nonprod
      BinaryMediaTypes:
        - multipart/form-data
      EndpointConfiguration:
        Type: REGIONAL
      Models:
        Picture:
          type: object
          # required:
          #   - image_src
          properties:
            image_src:
              type: string
            image_id:
              type: string
            image_tag:
              type: string
            image_collection:
              type: string
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-pictures-bucket
      AccessControl: public-read #Private  # Adjust access control as needed

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Events:
        GetPicture:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /picture
            Method: get
            RestApiId:
              Ref: RestApi

        UploadPicture:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /picture
            Method: post
            RequestModel:
              Model: Picture
              Required: true
              ValidateBody: true
            RestApiId:
              Ref: RestApi
            Asynchronous: 'true'  # Add this line to enable asynchronous invocation
        # S3Event:
        #   Type: S3
        #   Properties:
        #     Bucket: my-s3-bucket
        #     Events: s3:ObjectCreated:*  
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref MyS3Bucket

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
